"""Batch Crossref-filtered sources used to grow the catalog to 100 providers.

Each entry is a dedicated search connector that queries Crossref Works with a
container title and/or DOI prefix. Metadata-only publishers never bypass paywalls;
OA flags are set only for known open venues.
"""

from __future__ import annotations

# Provider-only keys are stripped when seeding the academic_sources table.
_PROVIDER_KEYS = frozenset({"prefix", "container", "work_type", "assume_oa", "publisher_name"})

BATCH_CROSSREF_SOURCES: list[dict[str, object]] = [
    {
        "slug": "mdpi",
        "display_name": "MDPI",
        "description": "MDPI open-access journals via Crossref DOI prefix.",
        "homepage_url": "https://www.mdpi.com",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://www.mdpi.com",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 540,
        "prefix": "10.3390",
        "assume_oa": True,
        "publisher_name": "MDPI",
    },
    {
        "slug": "frontiers",
        "display_name": "Frontiers",
        "description": "Frontiers open-access journals via Crossref DOI prefix.",
        "homepage_url": "https://www.frontiersin.org",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://www.frontiersin.org",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 550,
        "prefix": "10.3389",
        "assume_oa": True,
        "publisher_name": "Frontiers",
    },
    {
        "slug": "hindawi",
        "display_name": "Hindawi",
        "description": "Hindawi / Wiley open-access journals via Crossref DOI prefix.",
        "homepage_url": "https://www.hindawi.com",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://www.hindawi.com",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 560,
        "prefix": "10.1155",
        "assume_oa": True,
        "publisher_name": "Hindawi",
    },
    {
        "slug": "bmc",
        "display_name": "BMC",
        "description": "BioMed Central open-access journals via Crossref DOI prefix.",
        "homepage_url": "https://www.biomedcentral.com",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://www.biomedcentral.com",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 570,
        "prefix": "10.1186",
        "assume_oa": True,
        "publisher_name": "BioMed Central",
    },
    {
        "slug": "copernicus",
        "display_name": "Copernicus Publications",
        "description": "Copernicus open-access geoscience journals via Crossref DOI prefix.",
        "homepage_url": "https://publications.copernicus.org",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://publications.copernicus.org",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 580,
        "prefix": "10.5194",
        "assume_oa": True,
        "publisher_name": "Copernicus Publications",
    },
    {
        "slug": "preprints_org",
        "display_name": "Preprints.org",
        "description": "MDPI Preprints.org multidisciplinary preprint server.",
        "homepage_url": "https://www.preprints.org",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://www.preprints.org",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 590,
        "prefix": "10.20944",
        "assume_oa": True,
        "publisher_name": "Preprints.org",
    },
    {
        "slug": "socarxiv",
        "display_name": "SocArXiv",
        "description": "Social-science preprints (OSF / Crossref container).",
        "homepage_url": "https://osf.io/preprints/socarxiv",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://socopen.org",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 600,
        "container": "SocArXiv",
        "assume_oa": True,
        "publisher_name": "SocArXiv",
    },
    {
        "slug": "psyarxiv",
        "display_name": "PsyArXiv",
        "description": "Psychology preprints (OSF / Crossref DOI prefix).",
        "homepage_url": "https://osf.io/preprints/psyarxiv",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://psyarxiv.com",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 610,
        "prefix": "10.31234",
        "assume_oa": True,
        "publisher_name": "PsyArXiv",
    },
    {
        "slug": "engrxiv",
        "display_name": "engrXiv",
        "description": "Engineering preprints (OSF / Crossref container).",
        "homepage_url": "https://engrxiv.org",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://engrxiv.org",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 620,
        "container": "engrXiv",
        "assume_oa": True,
        "publisher_name": "engrXiv",
    },
    {
        "slug": "paleorxiv",
        "display_name": "PaleorXiv",
        "description": "Paleontology preprints (OSF / Crossref container).",
        "homepage_url": "https://osf.io/preprints/paleorxiv",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://paleorxiv.org",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 630,
        "container": "PaleorXiv",
        "assume_oa": True,
        "publisher_name": "PaleorXiv",
    },
    {
        "slug": "agrirxiv",
        "display_name": "AgriRxiv",
        "description": "Agriculture preprints via Crossref container metadata.",
        "homepage_url": "https://agrirxiv.org",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://agrirxiv.org",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 640,
        "container": "agriRxiv",
        "assume_oa": True,
        "publisher_name": "agriRxiv",
    },
    {
        "slug": "lawarxiv",
        "display_name": "LawArXiv",
        "description": "Law preprints (OSF / Crossref container).",
        "homepage_url": "https://osf.io/preprints/lawarxiv",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://osf.io/preprints/lawarxiv",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 650,
        "container": "LawArXiv",
        "assume_oa": True,
        "publisher_name": "LawArXiv",
    },
    {
        "slug": "metaarxiv",
        "display_name": "MetaArXiv",
        "description": "Metascience preprints (OSF / Crossref container).",
        "homepage_url": "https://osf.io/preprints/metaarxiv",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://osf.io/preprints/metaarxiv",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 660,
        "container": "MetaArXiv",
        "assume_oa": True,
        "publisher_name": "MetaArXiv",
    },
    {
        "slug": "africarxiv",
        "display_name": "AfricArXiv",
        "description": "African research preprints (OSF / Crossref container).",
        "homepage_url": "https://osf.io/preprints/africarxiv",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://info.africarxiv.org",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 670,
        "container": "AfricArXiv",
        "assume_oa": True,
        "publisher_name": "AfricArXiv",
    },
    {
        "slug": "ecoevorxiv",
        "display_name": "EcoEvoRxiv",
        "description": "Ecology and evolutionary biology preprints (OSF / Crossref).",
        "homepage_url": "https://osf.io/preprints/ecoevorxiv",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://ecoevorxiv.org",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 680,
        "container": "EcoEvoRxiv",
        "assume_oa": True,
        "publisher_name": "EcoEvoRxiv",
    },
    {
        "slug": "edarxiv",
        "display_name": "EdArXiv",
        "description": "Education research preprints (OSF / Crossref container).",
        "homepage_url": "https://osf.io/preprints/edarxiv",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://edarxiv.org",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 690,
        "container": "EdArXiv",
        "assume_oa": True,
        "publisher_name": "EdArXiv",
    },
    {
        "slug": "mediarxiv",
        "display_name": "MediArXiv",
        "description": "Media, film, and communication preprints (OSF / Crossref).",
        "homepage_url": "https://osf.io/preprints/mediarxiv",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://mediarxiv.org",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 700,
        "container": "MediArXiv",
        "assume_oa": True,
        "publisher_name": "MediArXiv",
    },
    {
        "slug": "sportrxiv",
        "display_name": "SportRxiv",
        "description": "Sport and exercise science preprints (OSF / Crossref).",
        "homepage_url": "https://osf.io/preprints/sportrxiv",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://osf.io/preprints/sportrxiv",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 710,
        "container": "SportRxiv",
        "assume_oa": True,
        "publisher_name": "SportRxiv",
    },
    {
        "slug": "wellcome_open",
        "display_name": "Wellcome Open Research",
        "description": "Wellcome Open Research articles via Crossref container metadata.",
        "homepage_url": "https://wellcomeopenresearch.org",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://wellcomeopenresearch.org",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 720,
        "container": "Wellcome Open Research",
        "assume_oa": True,
        "publisher_name": "Wellcome Open Research",
    },
    {
        "slug": "gates_open",
        "display_name": "Gates Open Research",
        "description": "Gates Open Research articles via Crossref container metadata.",
        "homepage_url": "https://gatesopenresearch.org",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://gatesopenresearch.org",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 730,
        "container": "Gates Open Research",
        "assume_oa": True,
        "publisher_name": "Gates Open Research",
    },
    {
        "slug": "scientific_reports",
        "display_name": "Scientific Reports",
        "description": "Nature Scientific Reports via Crossref container metadata.",
        "homepage_url": "https://www.nature.com/srep",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://www.nature.com/srep",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 740,
        "container": "Scientific Reports",
        "assume_oa": True,
        "publisher_name": "Nature Portfolio",
    },
    {
        "slug": "nature_communications",
        "display_name": "Nature Communications",
        "description": "Nature Communications via Crossref container metadata.",
        "homepage_url": "https://www.nature.com/ncomms",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://www.nature.com/ncomms",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 750,
        "container": "Nature Communications",
        "assume_oa": True,
        "publisher_name": "Nature Portfolio",
    },
    {
        "slug": "ieee_access",
        "display_name": "IEEE Access",
        "description": "IEEE Access open journal via Crossref container metadata.",
        "homepage_url": "https://ieeeaccess.ieee.org",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://ieeeaccess.ieee.org",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 760,
        "container": "IEEE Access",
        "assume_oa": True,
        "publisher_name": "IEEE",
    },
    {
        "slug": "optics_express",
        "display_name": "Optics Express",
        "description": "Optica Optics Express via Crossref container metadata.",
        "homepage_url": "https://opg.optica.org/oe",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://opg.optica.org/oe",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 770,
        "container": "Optics Express",
        "assume_oa": True,
        "publisher_name": "Optica",
    },
    {
        "slug": "royal_society",
        "display_name": "Royal Society",
        "description": "Royal Society journals via Crossref DOI prefix (metadata; OA when listed).",
        "homepage_url": "https://royalsociety.org/journals",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://royalsociety.org/journals",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 780,
        "prefix": "10.1098",
        "publisher_name": "The Royal Society",
    },
    {
        "slug": "iop",
        "display_name": "IOP Publishing",
        "description": "IOP Science journals via Crossref DOI prefix (metadata; OA when listed).",
        "homepage_url": "https://iopscience.iop.org",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://iopscience.iop.org",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 790,
        "prefix": "10.1088",
        "publisher_name": "IOP Publishing",
    },
    {
        "slug": "aip",
        "display_name": "AIP Publishing",
        "description": "American Institute of Physics journals via Crossref DOI prefix.",
        "homepage_url": "https://pubs.aip.org",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://pubs.aip.org",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 800,
        "prefix": "10.1063",
        "publisher_name": "AIP Publishing",
    },
    {
        "slug": "aps",
        "display_name": "American Physical Society",
        "description": "Physical Review journals via Crossref DOI prefix.",
        "homepage_url": "https://journals.aps.org",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://journals.aps.org",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 810,
        "prefix": "10.1103",
        "publisher_name": "American Physical Society",
    },
    {
        "slug": "acs",
        "display_name": "ACS Publications",
        "description": "American Chemical Society journals via Crossref DOI prefix.",
        "homepage_url": "https://pubs.acs.org",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://pubs.acs.org",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 820,
        "prefix": "10.1021",
        "publisher_name": "American Chemical Society",
    },
    {
        "slug": "rsc",
        "display_name": "Royal Society of Chemistry",
        "description": "RSC journals via Crossref DOI prefix (metadata; OA when listed).",
        "homepage_url": "https://www.rsc.org/journals-books-databases",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://www.rsc.org",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 830,
        "prefix": "10.1039",
        "publisher_name": "Royal Society of Chemistry",
    },
    {
        "slug": "agu",
        "display_name": "AGU Publications",
        "description": "American Geophysical Union journals via Crossref DOI prefix.",
        "homepage_url": "https://agupubs.onlinelibrary.wiley.com",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://www.agu.org/publications",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 840,
        "prefix": "10.1029",
        "publisher_name": "American Geophysical Union",
    },
    {
        "slug": "acm",
        "display_name": "ACM Digital Library",
        "description": "ACM publications via Crossref DOI prefix (metadata; OA when listed).",
        "homepage_url": "https://dl.acm.org",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://dl.acm.org",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 850,
        "prefix": "10.1145",
        "publisher_name": "Association for Computing Machinery",
    },
    {
        "slug": "wiley",
        "display_name": "Wiley",
        "description": "Wiley journals via Crossref DOI prefix (metadata; OA when listed).",
        "homepage_url": "https://onlinelibrary.wiley.com",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://onlinelibrary.wiley.com",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 860,
        "prefix": "10.1002",
        "publisher_name": "Wiley",
    },
    {
        "slug": "sage",
        "display_name": "SAGE Journals",
        "description": "SAGE journals via Crossref DOI prefix (metadata; OA when listed).",
        "homepage_url": "https://journals.sagepub.com",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://journals.sagepub.com",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 870,
        "prefix": "10.1177",
        "publisher_name": "SAGE Publications",
    },
    {
        "slug": "taylor_francis",
        "display_name": "Taylor & Francis",
        "description": "Taylor & Francis journals via Crossref DOI prefix (metadata; OA when listed).",
        "homepage_url": "https://www.tandfonline.com",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://www.tandfonline.com",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 880,
        "prefix": "10.1080",
        "publisher_name": "Taylor & Francis",
    },
    {
        "slug": "cambridge",
        "display_name": "Cambridge University Press",
        "description": "Cambridge journals via Crossref DOI prefix (metadata; OA when listed).",
        "homepage_url": "https://www.cambridge.org/core",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://www.cambridge.org/core",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 890,
        "prefix": "10.1017",
        "publisher_name": "Cambridge University Press",
    },
    {
        "slug": "oxford",
        "display_name": "Oxford Academic",
        "description": "Oxford University Press journals via Crossref DOI prefix.",
        "homepage_url": "https://academic.oup.com",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://academic.oup.com",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 900,
        "prefix": "10.1093",
        "publisher_name": "Oxford University Press",
    },
    {
        "slug": "bmj",
        "display_name": "BMJ",
        "description": "BMJ journals via Crossref DOI prefix (metadata; OA when listed).",
        "homepage_url": "https://www.bmj.com",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://www.bmj.com",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 910,
        "prefix": "10.1136",
        "publisher_name": "BMJ",
    },
    {
        "slug": "nejm",
        "display_name": "NEJM",
        "description": "New England Journal of Medicine via Crossref DOI prefix.",
        "homepage_url": "https://www.nejm.org",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://www.nejm.org",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 920,
        "prefix": "10.1056",
        "publisher_name": "Massachusetts Medical Society",
    },
    {
        "slug": "jama",
        "display_name": "JAMA Network",
        "description": "JAMA Network journals via Crossref DOI prefix.",
        "homepage_url": "https://jamanetwork.com",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://jamanetwork.com",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 930,
        "prefix": "10.1001",
        "publisher_name": "American Medical Association",
    },
    {
        "slug": "annual_reviews",
        "display_name": "Annual Reviews",
        "description": "Annual Reviews journals via Crossref DOI prefix.",
        "homepage_url": "https://www.annualreviews.org",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://www.annualreviews.org",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 940,
        "prefix": "10.1146",
        "publisher_name": "Annual Reviews",
    },
    {
        "slug": "mit_press",
        "display_name": "MIT Press",
        "description": "MIT Press journals and books via Crossref DOI prefix.",
        "homepage_url": "https://direct.mit.edu",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://mitpress.mit.edu",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 950,
        "prefix": "10.1162",
        "publisher_name": "MIT Press",
    },
    {
        "slug": "spie",
        "display_name": "SPIE",
        "description": "SPIE Digital Library via Crossref DOI prefix (optics / photonics).",
        "homepage_url": "https://www.spiedigitallibrary.org",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://www.spiedigitallibrary.org",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 960,
        "prefix": "10.1117",
        "publisher_name": "SPIE",
    },
    {
        "slug": "aiaa",
        "display_name": "AIAA",
        "description": "American Institute of Aeronautics and Astronautics via Crossref DOI prefix.",
        "homepage_url": "https://arc.aiaa.org",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://arc.aiaa.org",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 970,
        "prefix": "10.2514",
        "publisher_name": "AIAA",
    },
    {
        "slug": "asce",
        "display_name": "ASCE Library",
        "description": "American Society of Civil Engineers via Crossref DOI prefix.",
        "homepage_url": "https://ascelibrary.org",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://ascelibrary.org",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 980,
        "prefix": "10.1061",
        "publisher_name": "ASCE",
    },
    {
        "slug": "asme",
        "display_name": "ASME",
        "description": "American Society of Mechanical Engineers via Crossref DOI prefix.",
        "homepage_url": "https://asmedigitalcollection.asme.org",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://asmedigitalcollection.asme.org",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 990,
        "prefix": "10.1115",
        "publisher_name": "ASME",
    },
    {
        "slug": "degruyter",
        "display_name": "De Gruyter",
        "description": "De Gruyter journals via Crossref DOI prefix (metadata; OA when listed).",
        "homepage_url": "https://www.degruyter.com",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://www.degruyter.com",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 1000,
        "prefix": "10.1515",
        "publisher_name": "De Gruyter",
    },
]


def catalog_rows_from_batch() -> list[dict[str, object]]:
    """Return academic_sources seed rows (without provider-only Crossref fields)."""
    rows: list[dict[str, object]] = []
    for item in BATCH_CROSSREF_SOURCES:
        rows.append({key: value for key, value in item.items() if key not in _PROVIDER_KEYS})
    return rows


assert len(BATCH_CROSSREF_SOURCES) == 47, len(BATCH_CROSSREF_SOURCES)
assert len({str(item["slug"]) for item in BATCH_CROSSREF_SOURCES}) == 47
