"""Open-access science and technology ebook sources (official APIs only).

Fifty catalog entries, split by family (science vs technology) and focused on
data science, satellite technology, and electronics. Metadata-only publishers
never bypass paywalls; PDFs are taken only from OA book APIs and public
repositories (DOAB, OAPEN, OpenAlex books, Internet Archive texts, OpenStax,
NASA NTRS).
"""

from __future__ import annotations

# Provider-only keys are stripped when seeding academic_sources.
_PROVIDER_KEYS = frozenset(
    {
        "backend",
        "family",
        "category",
        "subject",
        "concept_id",
        "query_extra",
        "ia_clause",
        "content_kind",
    }
)

_DOAB = {
    "homepage_url": "https://www.doabooks.org",
    "api_base_url": "https://directory.doabooks.org/rest/search",
    "docs_url": "https://www.doabooks.org/en/resources/metadata-harvesting-and-content-dissemination",
}
_OAPEN = {
    "homepage_url": "https://www.oapen.org",
    "api_base_url": "https://library.oapen.org/rest/search",
    "docs_url": "https://www.oapen.org",
}
_OPENALEX = {
    "homepage_url": "https://openalex.org",
    "api_base_url": "https://api.openalex.org/works",
    "docs_url": "https://docs.openalex.org",
}
_IA = {
    "homepage_url": "https://archive.org",
    "api_base_url": "https://archive.org/advancedsearch.php",
    "docs_url": "https://archive.org/developers/",
}
_OPENSTAX = {
    "homepage_url": "https://openstax.org",
    "api_base_url": "https://openstax.org/apps/cms/api/books/",
    "docs_url": "https://openstax.org/tos",
}
_NTRS = {
    "homepage_url": "https://ntrs.nasa.gov",
    "api_base_url": "https://ntrs.nasa.gov/api/citations/search",
    "docs_url": "https://ntrs.nasa.gov/api/citations/docs",
}


def _row(
    *,
    slug: str,
    display_name: str,
    description: str,
    family: str,
    category: str,
    backend: str,
    sort_order: int,
    subject: str = "",
    concept_id: str = "",
    query_extra: str = "",
    ia_clause: str = "",
    urls: dict[str, str] | None = None,
) -> dict[str, object]:
    links = urls or {}
    return {
        "slug": slug,
        "display_name": display_name,
        "description": description,
        "homepage_url": links["homepage_url"],
        "api_base_url": links["api_base_url"],
        "docs_url": links["docs_url"],
        "requires_key": False,
        "api_key_env": None,
        "sort_order": sort_order,
        "backend": backend,
        "family": family,
        "category": category,
        "subject": subject,
        "concept_id": concept_id,
        "query_extra": query_extra,
        "ia_clause": ia_clause,
        "content_kind": "ebook",
    }


EBOOK_SOURCES: list[dict[str, object]] = [
    # Science · Data Science (10)
    _row(
        slug="doab_data_science",
        display_name="DOAB · Data Science",
        description="Open-access data science books from the Directory of Open Access Books.",
        family="science",
        category="Data Science",
        backend="doab",
        sort_order=1100,
        subject="data science",
        urls=_DOAB,
    ),
    _row(
        slug="oapen_data_science",
        display_name="OAPEN · Data Science",
        description="OAPEN library books tagged for data science and analytics.",
        family="science",
        category="Data Science",
        backend="oapen",
        sort_order=1110,
        subject="data science",
        urls=_OAPEN,
    ),
    _row(
        slug="openalex_books_ml",
        display_name="OpenAlex Books · Machine Learning",
        description="Open-access monographs in machine learning via OpenAlex type:book.",
        family="science",
        category="Data Science",
        backend="openalex",
        sort_order=1120,
        concept_id="C119857082",
        query_extra="machine learning",
        urls=_OPENALEX,
    ),
    _row(
        slug="openalex_books_ai",
        display_name="OpenAlex Books · Artificial Intelligence",
        description="Open-access AI monographs via OpenAlex.",
        family="science",
        category="Data Science",
        backend="openalex",
        sort_order=1130,
        concept_id="C154945302",
        query_extra="artificial intelligence",
        urls=_OPENALEX,
    ),
    _row(
        slug="ia_data_science",
        display_name="Internet Archive · Data Science",
        description="Public-domain and openly licensed data science texts on archive.org.",
        family="science",
        category="Data Science",
        backend="archive",
        sort_order=1140,
        ia_clause='subject:("data science" OR "machine learning" OR "data mining")',
        urls=_IA,
    ),
    _row(
        slug="doab_statistics",
        display_name="DOAB · Statistics",
        description="Open-access statistics and probability books from DOAB.",
        family="science",
        category="Data Science",
        backend="doab",
        sort_order=1150,
        subject="statistics",
        urls=_DOAB,
    ),
    _row(
        slug="oapen_statistics",
        display_name="OAPEN · Statistics",
        description="OAPEN statistics and quantitative methods books.",
        family="science",
        category="Data Science",
        backend="oapen",
        sort_order=1160,
        subject="statistics",
        urls=_OAPEN,
    ),
    _row(
        slug="openalex_books_statistics",
        display_name="OpenAlex Books · Statistics",
        description="Open-access statistics monographs via OpenAlex.",
        family="science",
        category="Data Science",
        backend="openalex",
        sort_order=1170,
        concept_id="C105795698",
        query_extra="statistics",
        urls=_OPENALEX,
    ),
    _row(
        slug="doab_artificial_intelligence",
        display_name="DOAB · Artificial Intelligence",
        description="DOAB open books in artificial intelligence.",
        family="science",
        category="Data Science",
        backend="doab",
        sort_order=1180,
        subject="artificial intelligence",
        urls=_DOAB,
    ),
    _row(
        slug="oapen_machine_learning",
        display_name="OAPEN · Machine Learning",
        description="OAPEN machine learning and statistical learning books.",
        family="science",
        category="Data Science",
        backend="oapen",
        sort_order=1190,
        subject="machine learning",
        urls=_OAPEN,
    ),
    # Science · Satellite / Earth observation (8)
    _row(
        slug="doab_remote_sensing",
        display_name="DOAB · Remote Sensing",
        description="Open-access remote sensing books from DOAB.",
        family="science",
        category="Satellite Technology",
        backend="doab",
        sort_order=1200,
        subject="remote sensing",
        urls=_DOAB,
    ),
    _row(
        slug="oapen_remote_sensing",
        display_name="OAPEN · Remote Sensing",
        description="OAPEN remote sensing and Earth observation books.",
        family="science",
        category="Satellite Technology",
        backend="oapen",
        sort_order=1210,
        subject="remote sensing",
        urls=_OAPEN,
    ),
    _row(
        slug="openalex_books_remote_sensing",
        display_name="OpenAlex Books · Remote Sensing",
        description="Open-access remote sensing monographs via OpenAlex.",
        family="science",
        category="Satellite Technology",
        backend="openalex",
        sort_order=1220,
        concept_id="C127313418",
        query_extra="remote sensing",
        urls=_OPENALEX,
    ),
    _row(
        slug="ia_remote_sensing",
        display_name="Internet Archive · Remote Sensing",
        description="Open texts on remote sensing and Earth observation at archive.org.",
        family="science",
        category="Satellite Technology",
        backend="archive",
        sort_order=1230,
        ia_clause='subject:("remote sensing" OR "earth observation" OR "satellite imagery")',
        urls=_IA,
    ),
    _row(
        slug="doab_earth_observation",
        display_name="DOAB · Earth Observation",
        description="DOAB books on Earth observation and geospatial science.",
        family="science",
        category="Satellite Technology",
        backend="doab",
        sort_order=1240,
        subject="earth observation",
        urls=_DOAB,
    ),
    _row(
        slug="nasa_ntrs_eo_books",
        display_name="NASA NTRS · Earth Observation",
        description="Public NASA technical reports on Earth observation and remote sensing.",
        family="science",
        category="Satellite Technology",
        backend="nasa_ntrs",
        sort_order=1250,
        query_extra="remote sensing earth observation satellite",
        urls=_NTRS,
    ),
    _row(
        slug="openalex_books_astronomy",
        display_name="OpenAlex Books · Astronomy",
        description="Open-access astronomy and space science monographs.",
        family="science",
        category="Satellite Technology",
        backend="openalex",
        sort_order=1260,
        concept_id="C105201057",
        query_extra="astronomy satellite",
        urls=_OPENALEX,
    ),
    _row(
        slug="doab_geoscience",
        display_name="DOAB · Geoscience",
        description="Open-access geoscience books relevant to satellite mapping.",
        family="science",
        category="Satellite Technology",
        backend="doab",
        sort_order=1270,
        subject="geoscience",
        urls=_DOAB,
    ),
    # Science · general STEM (7)
    _row(
        slug="doab_physics",
        display_name="DOAB · Physics",
        description="Open-access physics books from DOAB.",
        family="science",
        category="Science",
        backend="doab",
        sort_order=1280,
        subject="physics",
        urls=_DOAB,
    ),
    _row(
        slug="doab_chemistry",
        display_name="DOAB · Chemistry",
        description="Open-access chemistry books from DOAB.",
        family="science",
        category="Science",
        backend="doab",
        sort_order=1290,
        subject="chemistry",
        urls=_DOAB,
    ),
    _row(
        slug="doab_mathematics",
        display_name="DOAB · Mathematics",
        description="Open-access mathematics books from DOAB.",
        family="science",
        category="Science",
        backend="doab",
        sort_order=1300,
        subject="mathematics",
        urls=_DOAB,
    ),
    _row(
        slug="oapen_physics",
        display_name="OAPEN · Physics",
        description="OAPEN physics and applied physics books.",
        family="science",
        category="Science",
        backend="oapen",
        sort_order=1310,
        subject="physics",
        urls=_OAPEN,
    ),
    _row(
        slug="oapen_mathematics",
        display_name="OAPEN · Mathematics",
        description="OAPEN mathematics books.",
        family="science",
        category="Science",
        backend="oapen",
        sort_order=1320,
        subject="mathematics",
        urls=_OAPEN,
    ),
    _row(
        slug="openalex_books_physics",
        display_name="OpenAlex Books · Physics",
        description="Open-access physics monographs via OpenAlex.",
        family="science",
        category="Science",
        backend="openalex",
        sort_order=1330,
        concept_id="C121332964",
        query_extra="physics",
        urls=_OPENALEX,
    ),
    _row(
        slug="ia_science_texts",
        display_name="Internet Archive · Science",
        description="Open science textbooks and treatises on archive.org.",
        family="science",
        category="Science",
        backend="archive",
        sort_order=1340,
        ia_clause='subject:(science OR physics OR chemistry OR mathematics)',
        urls=_IA,
    ),
    # Technology · Electronics (10)
    _row(
        slug="doab_electronics",
        display_name="DOAB · Electronics",
        description="Open-access electronics books from DOAB.",
        family="technology",
        category="Electronics",
        backend="doab",
        sort_order=1400,
        subject="electronics",
        urls=_DOAB,
    ),
    _row(
        slug="oapen_electronics",
        display_name="OAPEN · Electronics",
        description="OAPEN electronics and circuits books.",
        family="technology",
        category="Electronics",
        backend="oapen",
        sort_order=1410,
        subject="electronics",
        urls=_OAPEN,
    ),
    _row(
        slug="openalex_books_electronics",
        display_name="OpenAlex Books · Electronics",
        description="Open-access electronics monographs via OpenAlex.",
        family="technology",
        category="Electronics",
        backend="openalex",
        sort_order=1420,
        concept_id="C107757080",
        query_extra="electronics",
        urls=_OPENALEX,
    ),
    _row(
        slug="ia_electronics",
        display_name="Internet Archive · Electronics",
        description="Open electronics and radio texts on archive.org.",
        family="technology",
        category="Electronics",
        backend="archive",
        sort_order=1430,
        ia_clause='subject:(electronics OR "electronic circuits" OR "radio engineering")',
        urls=_IA,
    ),
    _row(
        slug="doab_electrical_engineering",
        display_name="DOAB · Electrical Engineering",
        description="DOAB electrical engineering books.",
        family="technology",
        category="Electronics",
        backend="doab",
        sort_order=1440,
        subject="electrical engineering",
        urls=_DOAB,
    ),
    _row(
        slug="oapen_electrical_engineering",
        display_name="OAPEN · Electrical Engineering",
        description="OAPEN electrical engineering books.",
        family="technology",
        category="Electronics",
        backend="oapen",
        sort_order=1450,
        subject="electrical engineering",
        urls=_OAPEN,
    ),
    _row(
        slug="openalex_books_electrical",
        display_name="OpenAlex Books · Electrical Engineering",
        description="Open-access electrical engineering monographs.",
        family="technology",
        category="Electronics",
        backend="openalex",
        sort_order=1460,
        concept_id="C107757080",
        query_extra="electrical engineering",
        urls=_OPENALEX,
    ),
    _row(
        slug="doab_embedded_systems",
        display_name="DOAB · Embedded Systems",
        description="DOAB books on embedded systems and digital design.",
        family="technology",
        category="Electronics",
        backend="doab",
        sort_order=1470,
        subject="embedded systems",
        urls=_DOAB,
    ),
    _row(
        slug="openalex_books_circuits",
        display_name="OpenAlex Books · Circuits",
        description="Open-access circuit theory and VLSI monographs.",
        family="technology",
        category="Electronics",
        backend="openalex",
        sort_order=1480,
        concept_id="C107757080",
        query_extra="electronic circuits VLSI",
        urls=_OPENALEX,
    ),
    _row(
        slug="ia_electrical_engineering",
        display_name="Internet Archive · Electrical Engineering",
        description="Open electrical engineering texts on archive.org.",
        family="technology",
        category="Electronics",
        backend="archive",
        sort_order=1490,
        ia_clause='subject:("electrical engineering" OR "electric circuits")',
        urls=_IA,
    ),
    # Technology · Satellite engineering (8)
    _row(
        slug="doab_aerospace",
        display_name="DOAB · Aerospace",
        description="Open-access aerospace engineering books from DOAB.",
        family="technology",
        category="Satellite Technology",
        backend="doab",
        sort_order=1500,
        subject="aerospace",
        urls=_DOAB,
    ),
    _row(
        slug="oapen_aerospace",
        display_name="OAPEN · Aerospace",
        description="OAPEN aerospace and aeronautics books.",
        family="technology",
        category="Satellite Technology",
        backend="oapen",
        sort_order=1510,
        subject="aerospace",
        urls=_OAPEN,
    ),
    _row(
        slug="openalex_books_aerospace",
        display_name="OpenAlex Books · Aerospace",
        description="Open-access aerospace engineering monographs.",
        family="technology",
        category="Satellite Technology",
        backend="openalex",
        sort_order=1520,
        concept_id="C166957645",
        query_extra="aerospace satellite",
        urls=_OPENALEX,
    ),
    _row(
        slug="ia_aerospace",
        display_name="Internet Archive · Aerospace",
        description="Open aerospace and rocketry texts on archive.org.",
        family="technology",
        category="Satellite Technology",
        backend="archive",
        sort_order=1530,
        ia_clause='subject:(aerospace OR astronautics OR "space engineering" OR satellite)',
        urls=_IA,
    ),
    _row(
        slug="doab_satellite_engineering",
        display_name="DOAB · Satellite Engineering",
        description="DOAB books on satellites and space systems.",
        family="technology",
        category="Satellite Technology",
        backend="doab",
        sort_order=1540,
        subject="satellite",
        urls=_DOAB,
    ),
    _row(
        slug="openalex_books_spacecraft",
        display_name="OpenAlex Books · Spacecraft",
        description="Open-access spacecraft and satellite engineering monographs.",
        family="technology",
        category="Satellite Technology",
        backend="openalex",
        sort_order=1550,
        concept_id="C166957645",
        query_extra="spacecraft satellite engineering",
        urls=_OPENALEX,
    ),
    _row(
        slug="oapen_space_engineering",
        display_name="OAPEN · Space Engineering",
        description="OAPEN space systems and satellite engineering books.",
        family="technology",
        category="Satellite Technology",
        backend="oapen",
        sort_order=1560,
        subject="space engineering",
        urls=_OAPEN,
    ),
    _row(
        slug="nasa_ntrs_tech_books",
        display_name="NASA NTRS · Space Technology",
        description="Public NASA technical reports on spacecraft and satellite technology.",
        family="technology",
        category="Satellite Technology",
        backend="nasa_ntrs",
        sort_order=1570,
        query_extra="spacecraft satellite technology",
        urls=_NTRS,
    ),
    # Technology · computing / general (7)
    _row(
        slug="doab_computer_science",
        display_name="DOAB · Computer Science",
        description="Open-access computer science books from DOAB.",
        family="technology",
        category="Technology",
        backend="doab",
        sort_order=1580,
        subject="computer science",
        urls=_DOAB,
    ),
    _row(
        slug="oapen_computer_science",
        display_name="OAPEN · Computer Science",
        description="OAPEN computer science books.",
        family="technology",
        category="Technology",
        backend="oapen",
        sort_order=1590,
        subject="computer science",
        urls=_OAPEN,
    ),
    _row(
        slug="openalex_books_cs",
        display_name="OpenAlex Books · Computer Science",
        description="Open-access computer science monographs via OpenAlex.",
        family="technology",
        category="Technology",
        backend="openalex",
        sort_order=1600,
        concept_id="C41008148",
        query_extra="computer science",
        urls=_OPENALEX,
    ),
    _row(
        slug="ia_computers",
        display_name="Internet Archive · Computing",
        description="Open computing and programming texts on archive.org.",
        family="technology",
        category="Technology",
        backend="archive",
        sort_order=1610,
        ia_clause='subject:("computer science" OR computing OR programming)',
        urls=_IA,
    ),
    _row(
        slug="doab_software_engineering",
        display_name="DOAB · Software Engineering",
        description="DOAB software engineering books.",
        family="technology",
        category="Technology",
        backend="doab",
        sort_order=1620,
        subject="software engineering",
        urls=_DOAB,
    ),
    _row(
        slug="openstax_stem",
        display_name="OpenStax · STEM textbooks",
        description="Free peer-reviewed STEM textbooks from OpenStax (Rice University).",
        family="technology",
        category="Technology",
        backend="openstax",
        sort_order=1630,
        query_extra="science technology engineering",
        urls=_OPENSTAX,
    ),
    _row(
        slug="oapen_engineering",
        display_name="OAPEN · Engineering",
        description="OAPEN general engineering books.",
        family="technology",
        category="Technology",
        backend="oapen",
        sort_order=1640,
        subject="engineering",
        urls=_OAPEN,
    ),
]


def catalog_rows_from_ebooks() -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    for item in EBOOK_SOURCES:
        rows.append({key: value for key, value in item.items() if key not in _PROVIDER_KEYS})
    return rows


EBOOK_SOURCE_BY_SLUG: dict[str, dict[str, object]] = {str(item["slug"]): item for item in EBOOK_SOURCES}
EBOOK_SOURCE_SLUGS: frozenset[str] = frozenset(EBOOK_SOURCE_BY_SLUG)

assert len(EBOOK_SOURCES) == 50, len(EBOOK_SOURCES)
assert len(EBOOK_SOURCE_SLUGS) == 50
assert all(str(item["slug"]) not in {None, ""} for item in EBOOK_SOURCES)
