"""Built-in academic source catalog used to seed MySQL on first run."""

from __future__ import annotations

BUILTIN_SOURCES: list[dict[str, object]] = [
    {
        "slug": "openalex",
        "display_name": "OpenAlex",
        "description": "Open catalog of scholarly works, authors, and institutions.",
        "homepage_url": "https://openalex.org",
        "api_base_url": "https://api.openalex.org",
        "docs_url": "https://docs.openalex.org",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 10,
    },
    {
        "slug": "crossref",
        "display_name": "Crossref",
        "description": "DOI registration agency metadata for journal articles and proceedings.",
        "homepage_url": "https://www.crossref.org",
        "api_base_url": "https://api.crossref.org",
        "docs_url": "https://www.crossref.org/documentation/retrieve-metadata/rest-api/",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 20,
    },
    {
        "slug": "semantic_scholar",
        "display_name": "Semantic Scholar",
        "description": "AI-powered academic graph from the Allen Institute for AI.",
        "homepage_url": "https://www.semanticscholar.org",
        "api_base_url": "https://api.semanticscholar.org",
        "docs_url": "https://api.semanticscholar.org/api-docs",
        "requires_key": False,
        "api_key_env": "SEMANTIC_SCHOLAR_API_KEY",
        "sort_order": 30,
    },
    {
        "slug": "arxiv",
        "display_name": "arXiv",
        "description": "Open preprint archive for physics, CS, math, and related fields.",
        "homepage_url": "https://arxiv.org",
        "api_base_url": "https://export.arxiv.org/api/query",
        "docs_url": "https://info.arxiv.org/help/api/index.html",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 40,
    },
    {
        "slug": "pubmed",
        "display_name": "PubMed",
        "description": "NCBI biomedical literature search (E-utilities).",
        "homepage_url": "https://pubmed.ncbi.nlm.nih.gov",
        "api_base_url": "https://eutils.ncbi.nlm.nih.gov/entrez/eutils",
        "docs_url": "https://www.ncbi.nlm.nih.gov/books/NBK25501/",
        "requires_key": False,
        "api_key_env": "NCBI_API_KEY",
        "sort_order": 50,
    },
    {
        "slug": "europe_pmc",
        "display_name": "Europe PMC",
        "description": "Life-science literature with open-access full text where available.",
        "homepage_url": "https://europepmc.org",
        "api_base_url": "https://www.ebi.ac.uk/europepmc/webservices/rest",
        "docs_url": "https://europepmc.org/RestfulWebService",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 60,
    },
    {
        "slug": "core",
        "display_name": "CORE",
        "description": "Aggregator of open-access research papers worldwide.",
        "homepage_url": "https://core.ac.uk",
        "api_base_url": "https://api.core.ac.uk/v3/search/works",
        "docs_url": "https://api.core.ac.uk/docs/v3",
        "requires_key": True,
        "api_key_env": "CORE_API_KEY",
        "sort_order": 70,
    },
    {
        "slug": "doaj",
        "display_name": "DOAJ",
        "description": "Directory of Open Access Journals article search.",
        "homepage_url": "https://doaj.org",
        "api_base_url": "https://doaj.org/api/search/articles",
        "docs_url": "https://doaj.org/api/docs",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 80,
    },
    {
        "slug": "ieee",
        "display_name": "IEEE Xplore",
        "description": "IEEE publications search. Official API key required.",
        "homepage_url": "https://ieeexplore.ieee.org",
        "api_base_url": "https://ieeexploreapi.ieee.org/api/v1/search/articles",
        "docs_url": "https://developer.ieee.org",
        "requires_key": True,
        "api_key_env": "IEEE_API_KEY",
        "sort_order": 90,
    },
    {
        "slug": "springer",
        "display_name": "Springer Nature",
        "description": "Springer Nature Meta API. Official API key required.",
        "homepage_url": "https://www.springernature.com",
        "api_base_url": "https://api.springernature.com/meta/v2/json",
        "docs_url": "https://dev.springernature.com",
        "requires_key": True,
        "api_key_env": "SPRINGER_API_KEY",
        "sort_order": 100,
    },
    {
        "slug": "elsevier",
        "display_name": "Elsevier Scopus",
        "description": "Scopus search via Elsevier API. Official API key required.",
        "homepage_url": "https://www.elsevier.com",
        "api_base_url": "https://api.elsevier.com/content/search/scopus",
        "docs_url": "https://dev.elsevier.com",
        "requires_key": True,
        "api_key_env": "ELSEVIER_API_KEY",
        "sort_order": 110,
    },
    {
        "slug": "nasa_ads",
        "display_name": "NASA ADS",
        "description": "Astrophysics Data System bibliographic search. Token required.",
        "homepage_url": "https://ui.adsabs.harvard.edu",
        "api_base_url": "https://api.adsabs.harvard.edu/v1/search/query",
        "docs_url": "https://ui.adsabs.harvard.edu/help/api/",
        "requires_key": True,
        "api_key_env": "NASA_ADS_TOKEN",
        "sort_order": 120,
    },
]

SOURCE_KEY_FIELDS: dict[str, str] = {
    "semantic_scholar": "semantic_scholar_api_key",
    "core": "core_api_key",
    "springer": "springer_api_key",
    "elsevier": "elsevier_api_key",
    "ieee": "ieee_api_key",
    "pubmed": "ncbi_api_key",
    "nasa_ads": "nasa_ads_token",
}

SETTING_FIELDS: dict[str, str] = {
    "contact_email": "contact_email",
    "unpaywall_email": "unpaywall_email",
    "max_concurrent_requests": "max_concurrent_requests",
    "max_concurrent_downloads": "max_concurrent_downloads",
    "request_timeout_seconds": "request_timeout_seconds",
    "download_timeout_seconds": "download_timeout_seconds",
    "max_redirects": "max_redirects",
}

APP_SETTING_FIELDS: dict[str, str] = {
    "download_limit": "download_limit",
    "default_max_results": "default_max_results",
    "check_robots_txt": "check_robots_txt",
    "prefer_https": "prefer_https",
    "library_dir": "library_dir",
}

SECRET_SETTING_KEYS = {
    "semantic_scholar_api_key",
    "core_api_key",
    "springer_api_key",
    "elsevier_api_key",
    "ieee_api_key",
    "ncbi_api_key",
    "nasa_ads_token",
}
