"""Built-in academic source catalog used to seed MySQL on first run."""

from __future__ import annotations

BUILTIN_SOURCES: list[dict[str, object]] = [
    {
        "slug": "openalex",
        "display_name": "OpenAlex",
        "description": "Open catalog of scholarly works, authors, and institutions.",
        "homepage_url": "https://openalex.org",
        "api_base_url": "https://api.openalex.org",
        "docs_url": "https://docs.openalex.org",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 10,
    },
    {
        "slug": "crossref",
        "display_name": "Crossref",
        "description": "DOI registration agency metadata for journal articles and proceedings.",
        "homepage_url": "https://www.crossref.org",
        "api_base_url": "https://api.crossref.org",
        "docs_url": "https://www.crossref.org/documentation/retrieve-metadata/rest-api/",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 20,
    },
    {
        "slug": "semantic_scholar",
        "display_name": "Semantic Scholar",
        "description": "AI-powered academic graph from the Allen Institute for AI.",
        "homepage_url": "https://www.semanticscholar.org",
        "api_base_url": "https://api.semanticscholar.org",
        "docs_url": "https://api.semanticscholar.org/api-docs",
        "requires_key": False,
        "api_key_env": "SEMANTIC_SCHOLAR_API_KEY",
        "sort_order": 30,
    },
    {
        "slug": "arxiv",
        "display_name": "arXiv",
        "description": "Open preprint archive for physics, CS, math, and related fields.",
        "homepage_url": "https://arxiv.org",
        "api_base_url": "https://export.arxiv.org/api/query",
        "docs_url": "https://info.arxiv.org/help/api/index.html",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 40,
    },
    {
        "slug": "pubmed",
        "display_name": "PubMed",
        "description": "NCBI biomedical literature search (E-utilities).",
        "homepage_url": "https://pubmed.ncbi.nlm.nih.gov",
        "api_base_url": "https://eutils.ncbi.nlm.nih.gov/entrez/eutils",
        "docs_url": "https://www.ncbi.nlm.nih.gov/books/NBK25501/",
        "requires_key": False,
        "api_key_env": "NCBI_API_KEY",
        "sort_order": 50,
    },
    {
        "slug": "europe_pmc",
        "display_name": "Europe PMC",
        "description": "Life-science literature with open-access full text where available.",
        "homepage_url": "https://europepmc.org",
        "api_base_url": "https://www.ebi.ac.uk/europepmc/webservices/rest",
        "docs_url": "https://europepmc.org/RestfulWebService",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 60,
    },
    {
        "slug": "core",
        "display_name": "CORE",
        "description": "Aggregator of open-access research papers worldwide.",
        "homepage_url": "https://core.ac.uk",
        "api_base_url": "https://api.core.ac.uk/v3/search/works",
        "docs_url": "https://api.core.ac.uk/docs/v3",
        "requires_key": True,
        "api_key_env": "CORE_API_KEY",
        "sort_order": 70,
    },
    {
        "slug": "doaj",
        "display_name": "DOAJ",
        "description": "Directory of Open Access Journals article search.",
        "homepage_url": "https://doaj.org",
        "api_base_url": "https://doaj.org/api/search/articles",
        "docs_url": "https://doaj.org/api/docs",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 80,
    },
    {
        "slug": "ieee",
        "display_name": "IEEE Xplore",
        "description": "IEEE publications search. Official Metadata Search API key required (must be activated at developer.ieee.org).",
        "homepage_url": "https://ieeexplore.ieee.org",
        "api_base_url": "https://ieeexploreapi.ieee.org/api/v1/search/articles",
        "docs_url": "https://developer.ieee.org",
        "requires_key": True,
        "api_key_env": "IEEE_API_KEY",
        "sort_order": 90,
    },
    {
        "slug": "springer",
        "display_name": "Springer Nature",
        "description": "Springer Nature Meta API. Official API key required.",
        "homepage_url": "https://www.springernature.com",
        "api_base_url": "https://api.springernature.com/meta/v2/json",
        "docs_url": "https://dev.springernature.com",
        "requires_key": True,
        "api_key_env": "SPRINGER_API_KEY",
        "sort_order": 100,
    },
    {
        "slug": "elsevier",
        "display_name": "Elsevier Scopus",
        "description": "Scopus search via Elsevier API. Official API key required.",
        "homepage_url": "https://www.elsevier.com",
        "api_base_url": "https://api.elsevier.com/content/search/scopus",
        "docs_url": "https://dev.elsevier.com",
        "requires_key": True,
        "api_key_env": "ELSEVIER_API_KEY",
        "sort_order": 110,
    },
    {
        "slug": "nasa_ads",
        "display_name": "NASA ADS",
        "description": "Astrophysics Data System bibliographic search. Token required.",
        "homepage_url": "https://ui.adsabs.harvard.edu",
        "api_base_url": "https://api.adsabs.harvard.edu/v1/search/query",
        "docs_url": "https://ui.adsabs.harvard.edu/help/api/",
        "requires_key": True,
        "api_key_env": "NASA_ADS_TOKEN",
        "sort_order": 120,
    },
    {
        "slug": "nasa_ntrs",
        "display_name": "NASA NTRS",
        "description": "NASA Scientific and Technical Information repository. Public API, no key required.",
        "homepage_url": "https://ntrs.nasa.gov",
        "api_base_url": "https://ntrs.nasa.gov/api/citations/search",
        "docs_url": "https://sti.nasa.gov/harvesting-data-from-ntrs/",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 130,
    },
    {
        "slug": "openaire",
        "display_name": "OpenAIRE",
        "description": "European Open Science Graph of publications from repositories and journals.",
        "homepage_url": "https://www.openaire.eu",
        "api_base_url": "https://api.openaire.eu/graph/v3/research-products",
        "docs_url": "https://graph.openaire.eu/docs/apis/graph-api/research-products/",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 140,
    },
    {
        "slug": "hal",
        "display_name": "HAL",
        "description": "French national open archive (Hyper Articles en Ligne).",
        "homepage_url": "https://hal.science",
        "api_base_url": "https://api.archives-ouvertes.fr/search/",
        "docs_url": "https://api.archives-ouvertes.fr/docs",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 150,
    },
    {
        "slug": "zenodo",
        "display_name": "Zenodo",
        "description": "CERN open repository for papers, preprints, and research outputs.",
        "homepage_url": "https://zenodo.org",
        "api_base_url": "https://zenodo.org/api/records",
        "docs_url": "https://developers.zenodo.org",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 160,
    },
    {
        "slug": "dblp",
        "display_name": "DBLP",
        "description": "Computer science bibliography. Metadata search; OA PDFs via DOI/Unpaywall.",
        "homepage_url": "https://dblp.org",
        "api_base_url": "https://dblp.org/search/publ/api",
        "docs_url": "https://dblp.org/faq/How+can+I+fetch+DBLP+data.html",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 170,
    },
    {
        "slug": "plos",
        "display_name": "PLOS",
        "description": "Public Library of Science journals. All articles are open access.",
        "homepage_url": "https://plos.org",
        "api_base_url": "https://api.plos.org/search",
        "docs_url": "https://api.plos.org/",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 180,
    },
    {
        "slug": "eric",
        "display_name": "ERIC",
        "description": "U.S. education research index with public full text when ERIC hosts the PDF.",
        "homepage_url": "https://eric.ed.gov",
        "api_base_url": "https://api.ies.ed.gov/eric/",
        "docs_url": "https://eric.ed.gov/?api",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 190,
    },
    {
        "slug": "osti",
        "display_name": "DOE OSTI",
        "description": "U.S. Department of Energy scientific and technical reports.",
        "homepage_url": "https://www.osti.gov",
        "api_base_url": "https://www.osti.gov/api/v1/records",
        "docs_url": "https://www.osti.gov/api/v1/docs",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 200,
    },
    {
        "slug": "datacite",
        "display_name": "DataCite",
        "description": "DOI metadata for texts, reports, theses, and other research outputs.",
        "homepage_url": "https://datacite.org",
        "api_base_url": "https://api.datacite.org/dois",
        "docs_url": "https://support.datacite.org/docs/api",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 210,
    },
    {
        "slug": "osf",
        "display_name": "OSF Preprints",
        "description": "Open Science Framework preprint servers (OSF, PsyArXiv, SocArXiv, and others).",
        "homepage_url": "https://osf.io/preprints",
        "api_base_url": "https://api.osf.io/v2/preprints/",
        "docs_url": "https://developer.osf.io",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 220,
    },
    {
        "slug": "biorxiv",
        "display_name": "bioRxiv",
        "description": "Cold Spring Harbor biology preprints via Crossref container metadata.",
        "homepage_url": "https://www.biorxiv.org",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://www.biorxiv.org/about/FAQ",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 230,
    },
    {
        "slug": "medrxiv",
        "display_name": "medRxiv",
        "description": "Cold Spring Harbor health-science preprints via Crossref container metadata.",
        "homepage_url": "https://www.medrxiv.org",
        "api_base_url": "https://api.crossref.org/works",
        "docs_url": "https://www.medrxiv.org/about/FAQ",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 240,
    },
    {
        "slug": "figshare",
        "display_name": "Figshare",
        "description": "Open research repository for papers, posters, datasets, and preprints.",
        "homepage_url": "https://figshare.com",
        "api_base_url": "https://api.figshare.com/v2/articles",
        "docs_url": "https://docs.figshare.com",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 250,
    },
    {
        "slug": "doab",
        "display_name": "DOAB",
        "description": "Directory of Open Access Books from academic publishers.",
        "homepage_url": "https://www.doabooks.org",
        "api_base_url": "https://directory.doabooks.org/rest/search",
        "docs_url": "https://www.doabooks.org/en/doab/for-librarians-and-technical-staff",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 260,
    },
    {
        "slug": "scielo",
        "display_name": "SciELO",
        "description": "Latin American, Iberian, and South African open-access journal network.",
        "homepage_url": "https://scielo.org",
        "api_base_url": "https://search.scielo.org/",
        "docs_url": "https://www.scielo.org/en/about-scielo/open-access-statement/",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 270,
    },
    {
        "slug": "cinii",
        "display_name": "CiNii",
        "description": "National Institute of Informatics (Japan) article search.",
        "homepage_url": "https://cir.nii.ac.jp",
        "api_base_url": "https://cir.nii.ac.jp/opensearch/articles",
        "docs_url": "https://support.nii.ac.jp/en/cir/api",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 280,
    },
    {
        "slug": "inspire",
        "display_name": "INSPIRE-HEP",
        "description": "High-energy physics literature with arXiv and OA full text when listed.",
        "homepage_url": "https://inspirehep.net",
        "api_base_url": "https://inspirehep.net/api/literature",
        "docs_url": "https://github.com/inspirehep/rest-api-doc",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 290,
    },
    {
        "slug": "fatcat",
        "display_name": "Fatcat / IA Scholar",
        "description": "Internet Archive Scholar catalog of preserved open scholarly files.",
        "homepage_url": "https://fatcat.wiki",
        "api_base_url": "https://api.fatcat.wiki/v0/release/search",
        "docs_url": "https://guide.fatcat.wiki/fatcat_api.html",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 300,
    },
    {
        "slug": "worldbank",
        "display_name": "World Bank OKR",
        "description": "World Bank Open Knowledge Repository (DSpace 7 REST API).",
        "homepage_url": "https://openknowledge.worldbank.org",
        "api_base_url": "https://openknowledge.worldbank.org/server/api/discover/search/objects",
        "docs_url": "https://openknowledge.worldbank.org",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 310,
    },
    {
        "slug": "oapen",
        "display_name": "OAPEN",
        "description": "Open Access Publishing in European Networks — scholarly books.",
        "homepage_url": "https://www.oapen.org",
        "api_base_url": "https://library.oapen.org/rest/search",
        "docs_url": "https://www.oapen.org/about",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 320,
    },
    {
        "slug": "econstor",
        "display_name": "EconStor",
        "description": "ZBW open repository for economics working papers and articles.",
        "homepage_url": "https://www.econstor.eu",
        "api_base_url": "https://www.econstor.eu/rest/filtered-items",
        "docs_url": "https://www.econstor.eu/about",
        "requires_key": False,
        "api_key_env": None,
        "sort_order": 330,
    },
]

SOURCE_KEY_FIELDS: dict[str, str] = {
    "semantic_scholar": "semantic_scholar_api_key",
    "core": "core_api_key",
    "springer": "springer_api_key",
    "elsevier": "elsevier_api_key",
    "ieee": "ieee_api_key",
    "pubmed": "ncbi_api_key",
    "nasa_ads": "nasa_ads_token",
}

SETTING_FIELDS: dict[str, str] = {
    "contact_email": "contact_email",
    "unpaywall_email": "unpaywall_email",
    "max_concurrent_requests": "max_concurrent_requests",
    "max_concurrent_downloads": "max_concurrent_downloads",
    "request_timeout_seconds": "request_timeout_seconds",
    "download_timeout_seconds": "download_timeout_seconds",
    "max_redirects": "max_redirects",
}

APP_SETTING_FIELDS: dict[str, str] = {
    "download_limit": "download_limit",
    "default_max_results": "default_max_results",
    "check_robots_txt": "check_robots_txt",
    "prefer_https": "prefer_https",
    "library_dir": "library_dir",
}

SECRET_SETTING_KEYS = {
    "semantic_scholar_api_key",
    "core_api_key",
    "springer_api_key",
    "elsevier_api_key",
    "ieee_api_key",
    "ncbi_api_key",
    "nasa_ads_token",
}
